name = "pasteleria-hijitos"
compatibility_date = "2024-04-05"


[[d1_databases]]
binding = "DB"
database_name = "pasteleria-db"
database_id = "f7985336-a478-4502-84a5-8b40835559dc"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "pasteleria-assets"

# ==============================================================================
# ENTORNO DE STAGING (PRUEBAS)
# ==============================================================================
[vars]
R2_DOMAIN = "https://imagenes.pasteleriahijitos.cl"

[env.staging]
name = "pasteleria-hijitos-staging"


[[env.staging.d1_databases]]
binding = "DB"
database_name = "pasteleria-db-staging"
database_id = "f6441f94-2923-4388-8172-8e616c553ca7"

[[env.staging.r2_buckets]]
binding = "ASSETS"
bucket_name = "pasteleria-assets"

[env.staging.vars]
R2_DOMAIN = "https://imagenes.pasteleriahijitos.cl"

# Configuration for Cloudflare Pages Preview environments (all non-production branches)
[env.preview]

[[env.preview.d1_databases]]
binding = "DB"
database_name = "pasteleria-db-staging"
database_id = "f6441f94-2923-4388-8172-8e616c553ca7"

[[env.preview.r2_buckets]]
binding = "ASSETS"
bucket_name = "pasteleria-assets"

[env.preview.vars]
R2_DOMAIN = "https://imagenes.pasteleriahijitos.cl"
