name = "pasteleria-hijitos"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "pasteleria-db"
database_id = "f7985336-a478-4502-84a5-8b40835559dc"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "pasteleria-assets"


